site_name: Pinball Power-Up Controller & DMD
site_url: https://ppuc.org/
site_description: Pinball Poewer-Up Controller & DMD (PPUC) is a free and open-source pinball controller and display system.
use_directory_urls: true
repo_url: https://github.com/PPUCl/docs
repo_name: Website source on GitHub
edit_uri: blob/main/docs/

plugins:
  - search                # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
extra_css:
  - stylesheets/ppuc.css     # Sets our custom colors

markdown_extensions:
  - toc:                    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#table-of-contents
      title: On this page
  - attr_list               # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists
  - tables                  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/s#tables
  - admonition              # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - pymdownx.details        # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#details
  - pymdownx.superfences    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences
  - pymdownx.emoji:         # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:      # https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
      base_path: includes
      check_paths: true
      auto_append:
        - content_footer.md
  - pymdownx.keys           # https://facelessuser.github.io/pymdown-extensions/extensions/keys/

theme:
  name: material            # https://squidfunk.github.io
  logo: images/logo.png
  icon:
    # logo: material/checkbox-blank-circle
    repo: fontawesome/brands/github
    edit: fontawesome/solid/wand-magic-sparkles
  custom_dir: overrides     # https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme

  features:
    - navigation.instant    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    - navigation.footer     # https://squidfunk.github.io/mkdocs-material/upgrade/#navigationfooter
    - navigation.tabs       # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.indexes    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
    - navigation.top        # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - content.action.edit   # https://squidfunk.github.io/mkdocs-material/upgrade/#contentaction
    - toc.follow            # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-following
    - content.code.annotate # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations

  palette:                  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
    # Palette toggle for light mode
    - scheme: default       # specified in docs/stylesheets/ppuc.css
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate         # specified in docs/stylesheets/ppuc.css
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Open Sans
    code: Noto Sans Mono

extra:
  social:                                      # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/?h=social#social-links
    - icon: fontawesome/brands/github
      link: https://github.com/PPUC

nav:
- PPUC:
  - ppuc/index.md

- ZeDMD:
  - zedmd/index.md
