site_name: Pinball Power-Up Controller & DMD
site_url: https://ppuc.github.io/docs/
site_description: Pinball Power-Up Controller & DMD (PPUC) is a free and open-source pinball controller and display system.
use_directory_urls: true
repo_url: https://github.com/PPUC/docs
repo_name: Website source on GitHub
edit_uri: blob/main/docs/
docs_dir: docs

plugins:
  - search
extra_css:
  - stylesheets/ppuc.css

markdown_extensions:
  - toc:
      title: On this page
  - attr_list
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      base_path: includes
      check_paths: true
      auto_append:
        - content_footer.md
  - pymdownx.keys

theme:
  name: material
  logo: /docs/images/logo.png
  icon:
    repo: fontawesome/brands/github
    edit: fontawesome/solid/wand-magic-sparkles
  custom_dir: overrides

  features:
    - navigation.instant
    - navigation.footer
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.action.edit
    - toc.follow
    - content.code.annotate

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Open Sans
    code: Noto Sans Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PPUC
    - icon: fontawesome/brands/discord
      link: https://discord.gg/fkkk4MbBn5
      name: Join our Discord
  base_url: /docs/

nav:
  - Home:
    - index.md
  - PPUC:
    - ppuc/index.md
    - ppuc/config_tool.md
  - ZeDMD:
    - zedmd/index.md